package ai.nova.platform.policy.entity;

public enum PolicyType {
    MINIMUM_APPROVALS,
    CI_REQUIRED,
    NO_FAILED_CHECKS,
    SIGNED_COMMITS_REQUIRED,
    SEMANTIC_VERSION_REQUIRED,
    MANIFEST_INTEGRITY,
    RELEASE_NOTES_REQUIRED,
    DEPLOYMENT_OBSERVATION_EXISTS,
    ROLLBACK_PLAN_EXISTS,
    CUSTOM_EXPRESSION
}
