version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci

  - package-ecosystem: npm
    directory: /apps/portal
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - frontend

  - package-ecosystem: maven
    directory: /services/platform-api
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - backend

  - package-ecosystem: pip
    directory: /services/agent-runtime
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - agent-runtime
