package ai.nova.platform.tool.entity;

public enum ToolAuditAction {
    TOOL_CREATED,
    TOOL_UPDATED,
    TOOL_ACTIVATED,
    TOOL_ARCHIVED,
    TOOL_ASSIGNED,
    TOOL_UNASSIGNED,
    TOOL_CALL_REQUESTED,
    TOOL_CALL_APPROVED,
    TOOL_CALL_REJECTED,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_FAILED,
    TOOL_CALL_CANCELLED,
    TOOL_OUTPUT_TRUNCATED
}
