package ai.nova.platform.pullrequest.service;

import org.springframework.stereotype.Service;

import ai.nova.platform.git.dto.GitDtos.GitOperation;
import ai.nova.platform.orchestration.entity.AgentOrchestrationTask;
import ai.nova.platform.patch.dto.PatchDtos.PatchResult;
import ai.nova.platform.review.dto.ReviewDtos.ReviewResult;
import ai.nova.platform.testing.dto.TestingDtos.TestingResult;

@Service
public class PullRequestBodyBuilder {

    public String buildTitle(AgentOrchestrationTask task) {
        return "AI: Task #" + task.getId() + " — " + task.getDisplayName();
    }

    public String buildBody(
            AgentOrchestrationTask task,
            GitOperation gitOperation,
            PatchResult patch,
            ReviewResult review,
            TestingResult testing,
            String targetBranch) {
        StringBuilder body = new StringBuilder();
        body.append("## Summary\n\n");
        body.append("Automated implementation generated by Nova AI Platform for Task `")
                .append(task.getId())
                .append("`.\n\n");

        body.append("## Task\n\n");
        body.append("- Key: ").append(task.getTaskKey()).append('\n');
        body.append("- Title: ").append(task.getDisplayName()).append('\n');
        if (task.getDescription() != null && !task.getDescription().isBlank()) {
            body.append("- Description: ").append(task.getDescription().trim()).append('\n');
        }
        body.append('\n');

        body.append("## Review\n\n");
        if (review != null) {
            body.append("- Approved: ").append(review.approved() ? "Yes" : "No").append('\n');
            body.append("- Score: ").append(review.score()).append("/100\n");
            body.append("- Findings: ").append(review.findings().size()).append('\n');
            if (review.summary() != null && !review.summary().isBlank()) {
                body.append("- Summary: ").append(review.summary().trim()).append('\n');
            }
        } else {
            body.append("- Review result not available\n");
        }
        body.append('\n');

        body.append("## Testing\n\n");
        if (testing != null) {
            body.append("- Test suites generated: ").append(testing.generatedTests().size()).append('\n');
            body.append("- Test cases generated: ").append(testing.testCases().size()).append('\n');
            body.append("- Estimated coverage: ").append(testing.coverageEstimate()).append("%\n");
            if (testing.summary() != null && !testing.summary().isBlank()) {
                body.append("- Summary: ").append(testing.summary().trim()).append('\n');
            }
        } else {
            body.append("- Testing result not available\n");
        }
        body.append('\n');

        body.append("## Patch\n\n");
        if (patch != null && patch.statistics() != null) {
            body.append("- Files changed: ").append(patch.statistics().filesChanged()).append('\n');
            body.append("- Insertions: ").append(patch.statistics().insertions()).append('\n');
            body.append("- Deletions: ").append(patch.statistics().deletions()).append('\n');
        } else {
            body.append("- Patch statistics not available\n");
        }
        if (gitOperation != null && gitOperation.patchHash() != null) {
            body.append("- SHA-256: `").append(gitOperation.patchHash()).append("`\n");
        }
        body.append('\n');

        body.append("## Git\n\n");
        if (gitOperation != null) {
            body.append("- Branch: `").append(gitOperation.branchName()).append("`\n");
            body.append("- Commit: `").append(gitOperation.commitHash()).append("`\n");
        }
        body.append("- Base: `").append(targetBranch).append("`\n\n");

        body.append("## Safety\n\n");
        body.append("This Pull Request was created automatically.\n\n");
        body.append("It has not been approved, merged, or deployed automatically.\n\n");

        body.append("## Known limitations\n\n");
        body.append("- Automated agents may miss edge cases or integration constraints.\n");
        body.append("- Human review is required before merge.\n");

        return body.toString();
    }
}
